workspace:
  base: /go
  path: src/github.com/cblomart/vsphere-graphite

pipeline:
  build:
    image: golang:1.8
    commands:
    - go get
    - go build
    - echo ${COVERALLS_TOKEN}
    - go get github.com/mattn/goveralls
    - goveralls -v -service drone.io
