workspace:
  base: /go
  path: src/github.com/cblomart/vsphere-graphite

pipeline:
  deps:
    image: golang:1.8
    commands:
    - go get
  simplicity:
    image: golang:1.8
    group: sanity
    commands:
    - go get honnef.co/go/tools/cmd/gosimple
    - gosimple ./...
  coverage:
    image: golang:1.8
    group: sanity
    environment:
    - COVERALLS_TOKEN=${COVERALLS_TOKEN}
    commands:
    - go get github.com/mattn/goveralls
    - goveralls -service=drone.io
  build:
    image: golang:1.8
    commands:
    - go build
