workspace:
  base: /go
  path: src/github.com/cblomart/vsphere-graphite

pipeline:
  build:
    image: golang:1.8
    commands:
    - go get
    - go build
    - go get github.com/mattn/goveralls
    - goveralls -debug -service drone.io
